---
title: "Abstract ISEE 2026"
author:
  - name: Paulina Sell
    affiliation: Environmental Hygiene, German Environment Agency, Berlin, Germany
    orcid: 0009-0007-7419-2956
  - name: Margaux Sanchez
    affiliation: Agence nationale de sécurité sanitaire, Maisons-Alfort, France
    orcid: 
  - name: Philippe Palmont
    affiliation: Agence nationale de sécurité sanitaire, Maisons-Alfort, France
    orcid: 
  - name: Dietrich Plass
    affiliation: Environmental Hygiene, German Environment Agency, Berlin, Germany
    orcid: 0000-0002-8058-1399
date-modified: "2026-02-03"
bibliography: /Users/paulinasell/Documents/UBA/PARC/Metaanalysis_lead_IQloss/RProj/manuscript/references.bib
csl: /Users/paulinasell/Documents/UBA/PARC/Metaanalysis_lead_IQloss/RProj/manuscript/vancouver.csl
reference-section-title: "References"
format:
    html:
        toc: true
        title-block-banner: false
        number-sections: false
        embed-resources: true
        css: /Users/paulinasell/Documents/UBA/PARC/Metaanalysis_lead_IQloss/RProj/manuscript/custom.scss
        page-layout: full
        theme: yeti
---

## Information for Authors:
* Deadline: February 27, 2026 (23:59 CET)
* The submitting author is required to ensure that all co-authors are aware of the content of the abstract before submission

* Use acronyms only when necessary and define all non-standard abbreviations and concepts in your abstract at first use
* Abstract titles can contain a maximum of 20 words (no abbreviations)
* The abstract body should not exceed 300 words and should consist of the four sections: Objective, Material and Methods, Results, Conclusion.
* Phrases such as “results will be discussed” or “data will be presented” should not be used.
* Please mention all sources of funding for the work described and other acknowledgements briefly at the end of the abstract text.

* A main topic that is relevant for your abstract must be selected during the submission process. 
The Scientific Organizing Committee reserves the right to change the topics during the abstract review process.
* Please enter at least 2 to 5 keywords from the official keyword list

* Topic: A-10: Chemical exposures / A-18: Methods ?
* Keywords: Chemical exposures, Environmental epidemiology, Heavy metals, Lead, International collaboration, Modeling

## Abstract
### Objective
In epidemiology, evidence synthesis is often done by meta-analysis, primarily using a frequentist approach. Bayesian meta-analysis provides a framework for uncertainty quantification that incorporates both within-study and between-study variability and providing posterior distributions of the parameter of interest, facilitating transparent communication of uncertainty. The aim of this study is to compare a frequentist to a Bayesian approach and investigate how these frameworks influence exposure-response estimates, uncertainty characterisation, and applicability to further use of the results. The use case is the association of blood lead levels and children’s neurodevelopment.

### Material and Methods
We conducted a systematic review searching Pubmed and Scopus for studies on the association of blood lead levels and children’s neurodevelopment (operationalised as IQ score). Risk of bias (RoB) was assessed using the rapid RoB tool by Plate et al. 2024. All regression coefficients were harmonised to the loge scale before pooling and the same estimates were included in both meta-analyses. For the frequentist meta-analysis, we employed a random-effects model using the restricted maximum-likelihood estimation. For the Bayesian approach, we employed a hierarchical Bayesian random-effects model, with weakly-informative priors (main effect, mu: Normal(-1, 2), heterogeneity, tau: Normal+(0, 2)). We conducted sensitivity analyses to examine the sensitivity of the results to (1) possibly biased study results (RoB) and (2) the choice of priors. 

### Results


### Conclusion
Funding
